### ISSUE TITLE
Can not handle barrel files

### ISSUE THREAD

**Issue by timonkrebs** [angular-architects/detective#36]
# Issue

Run detective on https://github.com/angular/angular/tree/main/adev. 

You will get an error:
```shell
npx @softarc/detective detective

/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/sheriff-core/src/lib/file-info/get-ts-config-context.js:78
                throw new user_error_1.InvalidPathError(key, value);
                ^

InvalidPathError: invalid path mapping detected: selenium-webdriver: ./node_modules/@types/selenium-webdriver/index.d.ts. Please verify that the path exists.
    at getTsConfigContext (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/sheriff-core/src/lib/file-info/get-ts-config-context.js:78:23)
    at generateTsData (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/sheriff-core/src/lib/file-info/generate-ts-data.js:50:74)
    at init (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/sheriff-core/src/lib/main/init.js:21:58)
    at getProjectData (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/sheriff-core/src/lib/api/get-project-data.js:33:41)
    at /home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/detective/main.js:822:55
    at Array.map (<anonymous>)
    at inferDeps (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/detective/main.js:822:10)
    at /home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/detective/main.js:1475:27
    at /home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/detective/main.js:1493:3
    at Object.<anonymous> (/home/codespace/.npm/_npx/45f60c1b8fa1be30/node_modules/@softarc/detective/main.js:1495:12) {
  code: 'SH-001'
}
```

It does not work because of these files:
```csv
 /workspaces/angular/packages/platform-browser/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/common/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/common/http/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/core/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/router/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/core/rxjs-interop/src/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/forms/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/platform-browser/animations/async/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/animations/public_api.ts /workspaces/angular/adev
 /workspaces/angular/packages/platform-browser/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/common/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/common/http/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/core/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/router/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/core/rxjs-interop/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/forms/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/platform-browser/animations/async/index.ts /workspaces/angular/adev
 /workspaces/angular/packages/animations/index.ts /workspaces/angular/adev
```

**Comment by timonkrebs** [comment]
The same prolem seems to be present with https://github.com/gilsdav/ngx-translate-router. 
When I removed this in [tsconfig.json](https://github.com/gilsdav/ngx-translate-router/blob/6b4847b3a47c71ce278bce7abee86b786a0f974a/tsconfig.json#L32C1-L35C8) detective would start, but still not show team alignement correctly for dist:
```ts
      "@gilsdav/ngx-translate-router-scully-plugin": [
        "dist/ngx-translate-router-scully-plugin/ngx-translate-router-scully-plugin",
        "dist/ngx-translate-router-scully-plugin"
      ]
```

![image](https://github.com/user-attachments/assets/6b938e2d-8395-49d8-acd7-da89c836541a)

Would probably be good to also be able to filter directories, since dist is probably not of interest.
